add iterm2 symlink

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -170,5 +170,28 @@ ln -s $HOME/.dotfiles/bin $HOME/bin
 # symlink .dotfiles tmux to ~
 ln -s $HOME/.dotfiles/tmux $HOME/.tmux
 
+# symlink .itermcfg to ~
+ln -s $HOME/.dotfiles/iterm/.itermcfg.symlink $HOME/.itermcfg
+
+# # iterm2 config
+# echo ''
+# read -p "Do you currently use iTerm2 and would you like to set jldeen's custom colors? y/n" -n 1 -r
+# echo ''
+# if [[ $REPLY =~ ^[Yy]$ ]]
+# then
+# 	# Specify the preferences directory
+#   defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.itermcfg/"
+#   # Tell iTerm2 to use the custom preferences in the directory
+#   defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
+#     if [[ $? -eq 0 ]]
+#     then
+#         echo "Successfully configured iTerm2 to use jldeen's custom colors..."
+#     else
+#         echo "Failed to apply jldeen's custom colors..." >&2
+# fi
+# else 
+#     echo "You chose not to use iTerm2 or jldeen's custom colors."
+# fi
+
 echo ''
 echo '  All installed!'
